### ISSUE TITLE
“istio-knowledge-map-working-group/members” link is failure

### ISSUE THREAD

**Issue by dongzl** [servicemesher/istio-knowledge-map#3]
This link is failure in README.md document.
https://github.com/orgs/servicemesher/teams/istio-knowledge-map-working-group/members

**Comment by GuangmingLuo** [comment]
https://github.com/orgs/servicemesher/teams/istio-knowledge-map-wg/members

**Comment by SataQiu** [comment]
Fixed by https://github.com/servicemesher/istio-knowledge-map/commit/1153d251d317a68868bc2ef365abeb126d3dbb13
